apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: cXd1emVncXk=
  CLOUDINARY_KEY: NzE0MjQ3ODE3NjU3MzU3
  CLOUDINARY_SECRET: T2s4SF94SGRXZUgxeEx3OVo5R1REVjFiOEZB
  MAPBOX_TOKEN: LWIgcGsuZXlKMUlqb2ljbVZ6YUhVMk9DSXNJbUVpT2lKamJYVTJaMmwxYlRBd1kzQnhNbmh6T1hacWNteG9kVEU0SW4wLnJFT0pNSXZrWHlXSFpJX0ppZ3AzYVEK
  DB_URL: bW9uZ29kYitzcnY6Ly9yZXNobWE5NjIwMDJfZGJfdXNlcjpyZXNobWExMjNAbXlkZXBsb3kuNG9rcXJ1ci5tb25nb2RiLm5ldC8/YXBwTmFtZT1teWRlcGxveQ==
